services:
  # PostgreSQL FastAPI Server
  app_postgres:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
      - "8888:8888"
    environment:
      - APP_NAME=FastAPI PostgreSQL
      - DEBUG=true
      - API_PREFIX=/api/v1
      - SECRET_KEY=changethisinsecretkey
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      # PostgreSQL settings
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=fastapi
      # SQL Server specific settings
      - SQLSERVER_HOST=sqlserver
      - SQLSERVER_PORT=1433
      - SQLSERVER_USER=sa
      - SQLSERVER_PASSWORD=YourStrong@Passw0rd
      - SQLSERVER_DB=fastapi_db
    volumes:
      - ../:/app
    depends_on:
      - postgres
      - mysql
      - mongodb
      - sqlserver
    command: |
      /bin/sh -c 'sh /app/start.sh'
      
  # MongoDB FastAPI Server
  app_mongodb:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8000"
      - "8889:8888"
    environment:
      - APP_NAME=FastAPI MongoDB
      - DEBUG=true
      - API_PREFIX=/api/v1
      - SECRET_KEY=changethisinsecretkey
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      # MongoDB settings
      - DB_TYPE=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=mongodb
      - DB_PASSWORD=mongodb
      - DB_NAME=fastapi
    volumes:
      - ../:/app
    depends_on:
      - postgres
      - mysql
      - mongodb
      - sqlserver
    command: |
      /bin/sh -c 'sh /app/start.sh'
      
  # SQL Server FastAPI Server
  app_sqlserver:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8002:8000"
      - "8890:8888"
    environment:
      - APP_NAME=FastAPI SQL Server
      - DEBUG=true
      - API_PREFIX=/api/v1
      - SECRET_KEY=changethisinsecretkey
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      # SQL Server settings
      - DB_TYPE=sqlserver
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Passw0rd
      - DB_NAME=fastapi_db
    volumes:
      - ../:/app
    depends_on:
      - postgres
      - mysql
      - mongodb
      - sqlserver
    command: |
      /bin/sh -c 'sh /app/start.sh'

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=fastapi
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=fastapi
    volumes:
      - mongodb_data:/data/db
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  postgres_data:
  mysql_data:
  mongodb_data:
  sqlserver_data:
